version: '3.7'

services:
  agent:
    container_name: superblocks-worker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SUPERBLOCKS_AGENT_KEY=${SUPERBLOCKS_AGENT_KEY}
      # OPTIONAL
      - SUPERBLOCKS_AGENT_ENVIRONMENT=${SUPERBLOCKS_AGENT_ENVIRONMENT:-*}
      - SUPERBLOCKS_WORKER_TLS_INSECURE=${SUPERBLOCKS_WORKER_TLS_INSECURE:-true}
      - SUPERBLOCKS_AGENT_HOST_URL=${SUPERBLOCKS_AGENT_HOST_URL:-http://localhost:8020}
      - SUPERBLOCKS_AGENT_INTERNAL_HOST=${SUPERBLOCKS_AGENT_INTERNAL_HOST:-controller}
      - SUPERBLOCKS_AGENT_PORT=${SUPERBLOCKS_AGENT_PORT:-8020}
      - SUPERBLOCKS_WORKER_PORT=${SUPERBLOCKS_WORKER_PORT:-5001}
      - SUPERBLOCKS_WORKER_METRICS_PORT=${SUPERBLOCKS_WORKER_METRICS_PORT:-9090}
      # INTERNAL OVERRIDE
      - __SUPERBLOCKS_AGENT_SERVER_URL=${__SUPERBLOCKS_AGENT_SERVER_URL:-"https://app.superblocks.com"}
      # DEPRECATED
      - __SUPERBLOCKS_WORKER_ENABLE=true
    ports:
      - '${SUPERBLOCKS_WORKER_METRICS_PORT:-9090}:${SUPERBLOCKS_WORKER_METRICS_PORT:-9090}'
